gcp_region = "us-central1"
gcp_zone = "us-central1-c"
k8s_master_instance_type = "n1-standard-1"
k8s_node_instance_type = "n1-standard-1"
jenkins_master_instance_type = "n1-standard-1"
jenkins_slave_instance_type = "n1-standard-1"
